krstic_stat_films_homepage:
    path:     /krstic-stats-films
    defaults: { _controller: KrsticStatFilmsBundle:Home:index }
    
krstic_stat_films_uploadpage:
    path:     /krstic-stats-films-upload
    defaults: { _controller: KrsticStatFilmsBundle:Upload:index }
